<a href="https://colab.research.google.com/github/Waranika/My_machine_learning_study/blob/main/ML_tests.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import these libraries : 
* Panda (file importation)
* scikit-learn (for the algorithm application)
* numpy (for result accuracy calculation)





Install xlrd and pandas




In [8]:
from __future__ import print_function

import pandas as pd

from sklearn.utils import Bunch
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.pipeline import Pipeline

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression

import numpy as np

Get dataset


In [9]:
"""
While I use the avalaible datasets from the sklearn library, using pandas it's possible to import read files and put them to Bunch format

Example:
twenty_train = pd.read_csv("twenty_train.csv", header = 0, sep=";")
twenty_test = pd.read_csv("twenty_test.csv", header = 0, sep =";")
#Turn the files into Bunchs with respect to each columns
twenty_train = Bunch(data =  twenty_train["data"].fillna(' ').to_list(), targets = twenty_train["targets"].fillna(' ').to_list())
twenty_test = Bunch(data =  twenty_test["data"].fillna(' ').to_list(), targets = twenty_test["targets"].fillna(' ').to_list())
"""
from sklearn.datasets import fetch_20newsgroups
twenty_train = fetch_20newsgroups(subset='train', shuffle=True)
twenty_test = fetch_20newsgroups(subset='test', shuffle=True)

In [10]:
#We can print the categories that are going to get sorted
print(twenty_train.target_names)

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


*Naive Bayers* test

In [11]:
text_clf2 = Pipeline([('vect', CountVectorizer()),('tfidf', TfidfTransformer()),('clf', MultinomialNB()),])
text_clf2 = text_clf2.fit(twenty_train.data, twenty_train.target)

In [12]:
predicted = text_clf2.predict(twenty_test.data)
print (predicted)
np.mean(predicted == twenty_test.target)

[ 7 11  0 ...  9  3 15]


0.7738980350504514

In [13]:
pd.DataFrame(predicted)

0
0      7
1     11
2      0
3     17
4      0
...   ..
7527  14
7528   9
7529   9
7530   3
7531  15

[7532 rows x 1 columns]

*Support Vector Machine* test

In [14]:
text_clf_svm = Pipeline ([('vect', CountVectorizer()),('tfidf', TfidfTransformer()),('clf-svm', SGDClassifier(loss='hinge',penalty = 'l2', alpha = 1e-3, random_state = 42)),])
_=text_clf_svm.fit(twenty_train.data, twenty_train.target)

In [15]:
predicted_svm = text_clf_svm.predict(twenty_test.data)
print(predicted_svm)
np.mean(predicted_svm == twenty_test.target)

[ 7  1  0 ...  9  3 15]


0.8240839086563994

In [16]:
pd.DataFrame(predicted)

0
0      7
1     11
2      0
3     17
4      0
...   ..
7527  14
7528   9
7529   9
7530   3
7531  15

[7532 rows x 1 columns]



*Logistic regression* test


In [17]:
text_clf_svm2 = Pipeline ([('vect', CountVectorizer()),('tfidf', TfidfTransformer()),('clf-svm', LogisticRegression(penalty= 'l2', random_state = 42, max_iter=1000)),])
_=text_clf_svm2.fit(twenty_train.data, twenty_train.target)

In [19]:
import numpy as np
#libel_test.data = [libel_test.data]
predicted_svm2 = text_clf_svm2.predict(twenty_test.data)
print(predicted_svm2)
predicted_svm2 = text_clf_svm2.predict_proba(twenty_test.data)
print(predicted_svm2)
print(np.max(predicted_svm2))
np.mean(predicted_svm2 == twenty_test.target)

[ 7  1  0 ...  9 12 15]
[[0.02686339 0.05752885 0.02439325 ... 0.02407806 0.0299154  0.05978024]
 [0.01915529 0.1142262  0.06016651 ... 0.02173593 0.02020332 0.0221464 ]
 [0.6756914  0.0203766  0.0126069  ... 0.01252381 0.01133051 0.0455234 ]
 ...
 [0.04984748 0.03497598 0.04158874 ... 0.03114481 0.06143683 0.04032264]
 [0.01345978 0.03825559 0.03779792 ... 0.01297833 0.01228019 0.02544687]
 [0.07188697 0.01074818 0.00818726 ... 0.00792796 0.0268416  0.0708305 ]]
0.9874445414378156


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  


0.0